---
# handlers file for roles/config-sentinel

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Restart service redis-sentinel
  ansible.builtin.systemd:
    name: redis-sentinel
    state: restarted

- name: Enable service redis-sentinel
  ansible.builtin.systemd:
    name: redis-sentinel
    state: started
    enabled: yes