---
# tasks file for roles/config-sentinel

- name: Change mode daemonize
  ansible.builtin.lineinfile:
    path: /etc/redis-sentinel.conf
    regexp: '^daemonize'
    line: 'daemonize yes'

- name: Replace Redis Sentinel configuration file with IP Master
  ansible.builtin.lineinfile:
    path: /etc/redis-sentinel.conf
    regexp: '^sentinel monitor mymaster '
    line: 'sentinel monitor mymaster {{ hostvars[inventory_hostname].ansible_default_ipv4.address }} 6379 2'
  become: true
  with_items: "{{ groups['master'] }}"

- name: Replace Redis Sentinel configuration auth-pass
  ansible.builtin.lineinfile:
    path: /etc/redis-sentinel.conf
    regexp: '^# sentinel auth-pass '
    line: 'sentinel auth-pass mymaster basebs@'
  become: true
  
- name: Restart Redis Sentinel
  ansible.builtin.systemd:
    name: redis-sentinel
    state: restarted
  notify:
    - Reload systemd
    - Restart service redis-sentinel
    - Enable service redis-sentinel