---
# tasks file for roles/config-sentinel

- name: Edit /etc/redis-sentinel.conf
  ansible.builtin.blockinfile:
    path: /etc/redis-sentinel.conf
    block: |
      protected-mode no
      port 26379
      
      daemonize yes
      pidfile /var/run/redis-sentinel.pid
      logfile /var/log/redis/sentinel.log

      dir /tmp

      sentinel monitor mymaster {{ hostvars[inventory_hostname].ansible_default_ipv4.address }} 6379 2
      sentinel down-after-milliseconds mymaster 30000
      acllog-max-len 128

      sentinel parallel-syncs mymaster 1
      sentinel failover-timeout mymaster 180000
      sentinel deny-scripts-reconfig yes
      SENTINEL resolve-hostnames no
      SENTINEL announce-hostnames no
      SENTINEL master-reboot-down-after-period mymaster 0
      sentinel auth-pass mymaster basebs@
  with_items: "{{ groups['master'] }}"
  notify:
    - Restart sentinel
    - Enable sentinel
